<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PruebaDescripcionCuenta extends Seeder
{

    public function run(): void
    {
        DB::table('tbl_prueba_descripcion_cuenta')->insert(
            array(

               array(
                   'concepto_contable_id' => 140,
                   'descripcion' => 'SUBTOTAL CUENTA POR COBRAR: A TERCEROS',
                   'cuenta' => 138095,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 3,
                   'descripcion' => 'SUBTOTAL COMPRAS: PROPIEDAD RAIZ O EDIFICACIONES',
                   'cuenta' => 151605,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 8,
                   'descripcion' => 'SUBTOTAL COMPRAS: ACTIVOS FIJOS:CAJA FUERTE, ETC',
                   'cuenta' => 152410,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 186,
                   'descripcion' => 'SUBTOTAL SERVICIO DE DIGITACION',
                   'cuenta' => 170540,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 154,
                   'descripcion' => 'SUBTOTAL TRASLADO DE FONDOS SALIDA',
                   'cuenta' => 230505,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 250,
                   'descripcion' => 'SUBTOTAL TRASLADO DE FONDOS ENTRADA',
                   'cuenta' => 230505,
                   'movimiento' => 'C',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 167,
                   'descripcion' => 'SUBTOTAL TRASLADO DE FONDOS DATAFONO SALIDA',
                   'cuenta' => 230510,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 332,
                   'descripcion' => 'SUBTOTAL OPERACIONES EFECTY',
                   'cuenta' => 230535,
                   'movimiento' => 'D',
                       'iva' => 0.0,
                       'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 332,
                   'descripcion' => 'SUBTOTAL OPERACIONES EFECTY',
                   'cuenta' => 230535,
                   'movimiento' => 'C',
               'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 39,
                   'descripcion' => 'SUBTOTAL IMPUESTO: DE RETEICA',
                   'cuenta' => 236805,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 102,
                   'descripcion' => 'SUBTOTAL SS PF: ENTIDADES PROMOTORAS DE SALUD EPS',
                   'cuenta' => 237005,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 104,
                   'descripcion' => 'SUBTOTAL SS PF: ADMIN DE RIESGOS LABORALES, ARL',
                   'cuenta' => 237006,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 105,
                   'descripcion' => 'SUBTOTAL SS PF: CAJA DE COMPENSACION FAMILIAR',
                   'cuenta' => 237010,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 103,
                   'descripcion' => 'SUBTOTAL SS PF: FONDOS DE PENSIONES AFP',
                   'cuenta' => 237045,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 254,
                   'descripcion' => 'SUBTOTAL CUENTA POR PAGAR: A TERCEROS',
                   'cuenta' => 238095,
                   'movimiento' => 'C',
                   'iva'=> 0, 
                   'total' => 100,              
               ),
               array(
                   'concepto_contable_id' => 182,
                   'descripcion' => 'SUBTOTAL CXP A TERCEROS',
                   'cuenta' => 238095,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 141,
                   'descripcion' => 'SUBTOTAL CANCELACION PLAN SEPARE',
                   'cuenta' => 280505,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 286,
                   'descripcion' => 'SUBTOTAL ANTICIPO FABRICACIÓN JOYERÍA',
                   'cuenta' => 280505,
                   'movimiento' => 'C',
                   'iva'=> 0, 
                   'total' => 100,  
               ),
               array(
                   'concepto_contable_id' => 192,
                   'descripcion' => 'SUBTOTAL CANC. ANTICIPO FABRICACIÓN JOYERÍA',
                   'cuenta' => 280505,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 200,
                   'descripcion' => 'SUBTOTAL ABONO COMISIÓN MASRED',
                   'cuenta' => 280595,
                   'movimiento' => 'C',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 172,
                   'descripcion' => 'SUBTOTAL REVISORIA FISCAL',
                   'cuenta' => 511010,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 20,
                   'descripcion' => 'SUBTOTAL DOTACIÓN EMPLEADOS Y SUMINISTROS',
                   'cuenta' => 520551,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 105,
                   'descripcion' => 'SUBTOTAL DISTRIBUCIÓN CAJA COMP. FAMILIAR',
                   'cuenta' => 520572,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 166,
                   'descripcion' => 'SUBTOTAL ASCESORIAS COMERCIALES',
                   'cuenta' => 521015,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 5,
                   'descripcion' => 'SUBTOTAL ASESORIA EXTERNAS: JURIDICAS(ABOGADOS)',
                   'cuenta' => 521025,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 5,
                   'descripcion' => 'SUBTOTAL ASESORIA EXTERNAS: OTROS',
                   'cuenta' => 521095,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 40,
                   'descripcion' => 'SUBTOTAL IMPUESTO: INDUSTRIA Y COMERCIO',
                   'cuenta' => 521505,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 3,
                   'descripcion' => 'SUBTOTAL ARRENDMTO: PROP RAIZ(LOC) AGUIRRE E HIJO ',
                   'cuenta' => 522010,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 45,
                   'descripcion' => 'SUBTOTAL ARRENDMTO: EQUIPOS DE OFICINA ',
                   'cuenta' => 522020,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 5,
                   'descripcion' => 'SUBTOTAL ASESORIA EXTERNAS: FENACOVEN ',
                   'cuenta' => 522510,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
                array(
                    'concepto_contable_id' => 115,
                    'descripcion' => 'SUBTOTAL SRVCIO: ASEO Y VIGILANCIA ',
                    'cuenta' => 523505,
                    'movimiento' => 'D',
                    'iva' => 1.9,
                    'total' => 101.9,
                ),
                array(
                    'concepto_contable_id' => 115,
                    'descripcion' => 'SUBTOTAL REINTEGRO GASTO COMUN ASEO Y VIG ',
                    'cuenta' => 523505,
                    'movimiento' => 'C',
                    'iva' => 1.9,
                    'total' => 101.9,
                ),
               array(
                   'concepto_contable_id' => 125,
                   'descripcion' => 'SUBTOTAL SRVCIOS PUBLIC: AGUA Y ALCANTARILLADO ',
                   'cuenta' => 523525,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 121,
                   'descripcion' => 'SUBTOTAL SRVCIOS PUBLIC: ENERGÍA ',
                   'cuenta' => 523530,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 122,
                   'descripcion' => 'SUBTOTAL SRVCIOS PUBLIC: INTERNET JEFE ZONAL ',
                   'cuenta' => 523535,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 126,
                   'descripcion' => 'SUBTOTAL SRVCIOS PUBLIC: AVANTEL ',
                   'cuenta' => 523535,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 123,
                   'descripcion' => 'SUBTOTAL SRVCIOS PUBLIC: TELÉFONO ',
                   'cuenta' => 523535,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 97,
                   'descripcion' => 'SUBTOTAL PUBLICIDAD: RADIAL ',
                   'cuenta' => 523560,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 127,
                   'descripcion' => 'SUBTOTAL SRVCIOS PUBLIC: OTRAS ENTIDADES ',
                   'cuenta' => 523595,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 199,
                   'descripcion' => 'SUBTOTAL SERVICIO LOGISTICA ',
                   'cuenta' => 523595,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 111,
                   'descripcion' => 'SUBTOTAL SRVCIO: GARANTÍA ART. ARREGLO JOYAS-ELEC ',
                   'cuenta' => 524515,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 45,
                   'descripcion' => 'SUBTOTAL MANTNMTO: EQUIPOS ELECTRÓNICOS ',
                   'cuenta' => 524515,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 15,
                   'descripcion' => 'SUBTOTAL COMPRAS: INSUMOS CONTRATACION Y VENTAS ',
                   'cuenta' => 524515,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 45,
                   'descripcion' => 'SUBTOTAL MANTNMTO: EQUIPOS DE COMPUTO ',
                   'cuenta' => 524525,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 50,
                   'descripcion' => 'SUBTOTAL ADEC LOCATIVAS: INSTALACIONES ELECTRICAS ',
                   'cuenta' => 525005,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 50,
                   'descripcion' => 'SUBTOTAL MANTNMTO: REPARA ELECTRICAS-ALARMAVISIÓN ',
                   'cuenta' => 525005,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 131,
                   'descripcion' => 'SUBTOTAL SOSTNMTO LOCAL: ADECUACIONES LOCATIVAS ',
                   'cuenta' => 525015,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 200,
                   'descripcion' => 'SUBTOTAL COMISIÓN MASRED ',
                   'cuenta' => 529505,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 12,
                   'descripcion' => 'SUBTOTAL COMPRAS: ELEMENTOS DE ASEO ',
                   'cuenta' => 529525,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 11,
                   'descripcion' => 'SUBTOTAL COMPRAS: ELEMENTOS CAFETERÍA IVA19% ',
                   'cuenta' => 529525,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 17,
                   'descripcion' => 'SUBTOTAL COMPRAS: UTILES DE PAPELERÍA ',
                   'cuenta' => 529530,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 16,
                   'descripcion' => 'SUBTOTAL COMPRAS: LITOGRAFIA ',
                   'cuenta' => 529530,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 114,
                   'descripcion' => 'SUBTOTAL SRVCIO: RESTAURANTE ',
                   'cuenta' => 529560,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 114,
                   'descripcion' => 'SUBTOTAL REITEGRO GASTO COMUN RESTAURANTE ',
                   'cuenta' => 529560,
                   'movimiento' => 'C',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 165,
                   'descripcion' => 'SUBTOTAL TRANSFORMACIÒN DE ORO',
                   'cuenta' => 14351005,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 243,
                   'descripcion' => 'SUBTOTAL COMPRA DE INVENTARIO EN CONSIGNACIÓN',
                   'cuenta' => 14353010,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,

               ),
               array(
                   'concepto_contable_id' => 140,
                   'descripcion' => 'IVA CUENTA POR COBRAR: A TERCEROS ',
                   'cuenta' => 0,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 3,
                   'descripcion' => 'IVA COMPRAS: PROPIEDAD RAIZ O EDIFICACIONES',
                   'cuenta' => 151699,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 8,
                   'descripcion' => 'IVA COMPRAS: ACTIVOS FIJOS:CAJA FUERTE, ETC',
                   'cuenta' => 152499,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 186,
                   'descripcion' => 'IVA SERVICIO DE DIGITACION',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 154,
                   'descripcion' => 'IVA TRASLADO DE FONDOS SALIDA',
                   'cuenta' => 0,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 167,
                   'descripcion' => 'IVA TRASLADO DE FONDOS DATAFONO SALIDA',
                   'cuenta' => 0,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 332,
                   'descripcion' => 'IVA OPERACIONES EFECTY',
                   'cuenta' => 0,
                   'movimiento' => 'D',
               'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 39,
                   'descripcion' => 'IVA IMPUESTO: DE RETEICA',
                   'cuenta' => 0,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 102,
                   'descripcion' => 'IVA SS PF: ENTIDADES PROMOTORAS DE SALUD EPS',
                   'cuenta' => 0,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 104,
                   'descripcion' => 'IVA SS PF: ADMIN DE RIESGOS LABORALES, ARL',
                   'cuenta' => 0,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 105,
                   'descripcion' => 'IVA SS PF: CAJA DE COMPENSACION FAMILIAR',
                   'cuenta' => 0,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 103,
                   'descripcion' => 'IVA SS PF: FONDOS DE PENSIONES AFP',
                   'cuenta' => 0,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 182,
                   'descripcion' => 'IVA CXP A TERCEROS',
                   'cuenta' => 0,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 141,
                   'descripcion' => 'IVA CANCELACION PLAN SEPARE',
                   'cuenta' => 0,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 192,
                   'descripcion' => 'IVA CANC. ANTICIPO FABRICACIÓN JOYERÍA',
                   'cuenta' => 0,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 172,
                   'descripcion' => 'IVA REVISORIA FISCAL',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 20,
                   'descripcion' => 'IVA DOTACIÓN EMPLEADOS Y SUMINISTROS',
                   'cuenta' => 240816,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 105,
                   'descripcion' => 'IVA DISTRIBUCIÓN CAJA COMP. FAMILIAR ',
                   'cuenta' => 0,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 166,
                   'descripcion' => 'IVA ASCESORIAS COMERCIALES',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 5,
                   'descripcion' => 'IVA ASESORIA EXTERNAS: JURIDICAS(ABOGADOS)',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 5,
                   'descripcion' => 'IVA ASESORIA EXTERNAS: OTROS',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 40,
                   'descripcion' => 'IVA IMPUESTO: INDUSTRIA Y COMERCIO',
                   'cuenta' => 0,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 3,
                   'descripcion' => 'IVA ARRENDMTO: PROP RAIZ(LOC) AGUIRRE E HIJO',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 45,
                   'descripcion' => 'IVA ARRENDMTO: EQUIPOS DE OFICINA',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 5,
                   'descripcion' => 'IVA ASESORIA EXTERNAS: FENACOVEN',
                   'cuenta' => 0,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 115,
                   'descripcion' => 'IVA SRVCIO: ASEO Y VIGILANCIA',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 1.9,
                   'total' => 101.9,
               ),
               array(
                   'concepto_contable_id' => 125,
                   'descripcion' => 'IVA SRVCIOS PUBLIC: AGUA Y ALCANTARILLADO',
                   'cuenta' => 0,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 121,
                   'descripcion' => 'IVA SRVCIOS PUBLIC: ENERGÍA',
                   'cuenta' => 0,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 122,
                   'descripcion' => 'IVA SRVCIOS PUBLIC: INTERNET JEFE ZONAL',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 126,
                   'descripcion' => 'IVA SRVCIOS PUBLIC: AVANTEL',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 123,
                   'descripcion' => 'IVA SRVCIOS PUBLIC: TELÉFONO',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 122,
                   'descripcion' => 'IVA SRVCIOS PUBLIC: INTERNET',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 97,
                   'descripcion' => 'IVA PUBLICIDAD: RADIAL',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 127,
                   'descripcion' => 'IVA SRVCIOS PUBLIC: OTRAS ENTIDADES',
                   'cuenta' => 0,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 199,
                   'descripcion' => 'IVA SERVICIO LOGISTICA',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 111,
                   'descripcion' => 'IVA SRVCIO: GARANTÍA ART. ARREGLO JOYAS-ELEC',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 45,
                   'descripcion' => 'IVA MANTNMTO: EQUIPOS ELECTRÓNICOS',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 15,
                   'descripcion' => 'IVA COMPRAS: INSUMOS CONTRATACION Y VENTAS',
                   'cuenta' => 240816,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 45,
                   'descripcion' => 'IVA MANTNMTO: EQUIPOS DE COMPUTO',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 50,
                   'descripcion' => 'IVA ADEC LOCATIVAS: INSTALACIONES ELECTRICAS',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 50,
                   'descripcion' => 'IVA MANTNMTO: REPARA ELECTRICAS-ALARMAVISIÓN',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 131,
                   'descripcion' => 'IVA SOSTNMTO LOCAL: ADECUACIONES LOCATIVAS',
                   'cuenta' => 240816,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 200,
                   'descripcion' => 'IVA COMISIÓN MASRED',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 12,
                   'descripcion' => 'IVA COMPRAS: ELEMENTOS DE ASEO',
                   'cuenta' => 240816,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 11,
                   'descripcion' => 'IVA COMPRAS: ELEMENTOS CAFETERÍA IVA19%',
                   'cuenta' => 240816,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 17,
                   'descripcion' => 'IVA COMPRAS: UTILES DE PAPELERÍA',
                   'cuenta' => 240816,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 16,
                   'descripcion' => 'IVA COMPRAS: LITOGRAFIA',
                   'cuenta' => 240816,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 114,
                   'descripcion' => 'IVA SRVCIO: RESTAURANTE',
                   'cuenta' => 0,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 165,
                   'descripcion' => 'IVA TRANSFORMACIÒN DE ORO',
                   'cuenta' => 240821,
                   'movimiento' => 'D',
                   'iva' => 19,
                   'total' => 119,
               ),
               array(
                   'concepto_contable_id' => 243,
                   'descripcion' => 'IVA COMPRA DE INVENTARIO EN CONSIGNACIÓN',
                   'cuenta' => 240816,
                   'movimiento' => 'D',
                   'iva' => 0.0,
                   'total' => 100,

               ),
               array(
                   'concepto_contable_id' => 250,
                   'descripcion' => 'TOTAL TRASLADO DE FONDOS ENTRADA',
                   'cuenta' => 110505,
                   'movimiento' => 'C',
                   'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 332,
                   'descripcion' => 'TOTAL OPERACIONES EFECTY',
                   'cuenta' => 110505,
                   'movimiento' => 'C',
               'iva' => 0.0,
                   'total' => 100,
               ),
               array(
                   'concepto_contable_id' => 254,
                   'descripcion' => 'TOTAL CUENTA POR PAGAR: A TERCEROS',
                   'cuenta' => 110505,
                   'movimiento' => 'C',
                   'iva'=> 0, 
                   'total' => 100,  
               ),
               array(
                   'concepto_contable_id' => 286,
                   'descripcion' => 'TOTAL ANTICIPO FABRICACIÓN JOYERÍA',
                   'cuenta' => 110505,
                   'movimiento' => 'C',
                   'iva'=> 0, 
                   'total' => 100,  
               ),
               array(
                   'concepto_contable_id' => 200,
                   'descripcion' => 'TOTAL ABONO COMISIÓN MASRED',
                   'cuenta' => 110505,
                   'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 115,
                     'descripcion' => 'TOTAL REINTEGRO GASTO COMUN ASEO Y VIG',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 1.9,
                     'total' => 101.9,
                 ),
                 array(
                     'concepto_contable_id' => 114,
                     'descripcion' => 'TOTAL REITEGRO GASTO COMUN RESTAURANTE',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 140,
                     'descripcion' => 'TOTAL CUENTA POR COBRAR: A TERCEROS',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 3,
                     'descripcion' => 'TOTAL COMPRAS: PROPIEDAD RAIZ O EDIFICACIONES',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 8,
                     'descripcion' => 'TOTAL COMPRAS: ACTIVOS FIJOS:CAJA FUERTE, ETC',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 186,
                     'descripcion' => 'TOTAL SERVICIO DE DIGITACION',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 154,
                     'descripcion' => 'TOTAL TRASLADO DE FONDOS SALIDA',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 167,
                     'descripcion' => 'TOTAL TRASLADO DE FONDOS DATAFONO SALIDA',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 332,
                     'descripcion' => 'TOTAL OPERACIONES EFECTY',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                 'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 39,
                     'descripcion' => 'TOTAL IMPUESTO: DE RETEICA',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 102,
                     'descripcion' => 'TOTAL SS PF: ENTIDADES PROMOTORAS DE SALUD EPS',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 104,
                     'descripcion' => 'TOTAL SS PF: ADMIN DE RIESGOS LABORALES, ARL',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 105,
                     'descripcion' => 'TOTAL SS PF: CAJA DE COMPENSACION FAMILIAR',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 103,
                     'descripcion' => 'TOTAL SS PF: FONDOS DE PENSIONES AFP',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 182,
                     'descripcion' => 'TOTAL CXP A TERCEROS',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 141,
                     'descripcion' => 'TOTAL CANCELACION PLAN SEPARE',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 192,
                     'descripcion' => 'TOTAL CANC. ANTICIPO FABRICACIÓN JOYERÍA',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 172,
                     'descripcion' => 'TOTAL REVISORIA FISCAL',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 20,
                     'descripcion' => 'TOTAL DOTACIÓN EMPLEADOS Y SUMINISTROS',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 105,
                     'descripcion' => 'TOTAL DISTRIBUCIÓN CAJA COMP. FAMILIAR',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 166,
                     'descripcion' => 'TOTAL ASCESORIAS COMERCIALES',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),

                 array(
                     'concepto_contable_id' => 5,
                     'descripcion' => 'TOTAL ASESORIA EXTERNAS: JURIDICAS(ABOGADOS)',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 5,
                     'descripcion' => 'TOTAL ASESORIA EXTERNAS: OTROS',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 40,
                     'descripcion' => 'TOTAL IMPUESTO: INDUSTRIA Y COMERCIO',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 3,
                     'descripcion' => 'TOTAL ARRENDMTO: PROP RAIZ(LOC) AGUIRRE E HIJO',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 45,
                     'descripcion' => 'TOTAL ARRENDMTO: EQUIPOS DE OFICINA',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 5,
                     'descripcion' => 'TOTAL ASESORIA EXTERNAS: FENACOVEN',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 115,
                     'descripcion' => 'TOTAL SRVCIO: ASEO Y VIGILANCIA',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 1.9,
                     'total' => 101.9,
                 ),
                 array(
                     'concepto_contable_id' => 125,
                     'descripcion' => 'TOTAL SRVCIOS PUBLIC: AGUA Y ALCANTARILLADO',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 121,
                     'descripcion' => 'TOTAL SRVCIOS PUBLIC: ENERGÍA',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 122,
                     'descripcion' => 'TOTAL SRVCIOS PUBLIC: INTERNET JEFE ZONAL',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 126,
                     'descripcion' => 'TOTAL SRVCIOS PUBLIC: AVANTEL',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 123,
                     'descripcion' => 'TOTAL SRVCIOS PUBLIC: TELÉFONO',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 122,
                     'descripcion' => 'TOTAL SRVCIOS PUBLIC: INTERNET',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 97,
                     'descripcion' => 'TOTAL PUBLICIDAD: RADIAL',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 127,
                     'descripcion' => 'TOTAL SRVCIOS PUBLIC: OTRAS ENTIDADES',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 199,
                     'descripcion' => 'TOTAL SERVICIO LOGISTICA',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 111,
                     'descripcion' => 'TOTAL SRVCIO: GARANTÍA ART. ARREGLO JOYAS-ELEC',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 45,
                     'descripcion' => 'TOTAL MANTNMTO: EQUIPOS ELECTRÓNICOS',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 15,
                     'descripcion' => 'TOTAL COMPRAS: INSUMOS CONTRATACION Y VENTAS',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 45,
                     'descripcion' => 'TOTAL MANTNMTO: EQUIPOS DE COMPUTO',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 50,
                     'descripcion' => 'TOTAL ADEC LOCATIVAS: INSTALACIONES ELECTRICAS',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 50,
                     'descripcion' => 'TOTAL MANTNMTO: REPARA ELECTRICAS-ALARMAVISIÓN',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 131,
                     'descripcion' => 'TOTAL SOSTNMTO LOCAL: ADECUACIONES LOCATIVAS',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 200,
                     'descripcion' => 'TOTAL COMISIÓN MASRED',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 12,
                     'descripcion' => 'TOTAL COMPRAS: ELEMENTOS DE ASEO',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 11,
                     'descripcion' => 'TOTAL COMPRAS: ELEMENTOS CAFETERÍA IVA19%',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 17,
                     'descripcion' => 'TOTAL COMPRAS: UTILES DE PAPELERÍA',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 16,
                     'descripcion' => 'TOTAL COMPRAS: LITOGRAFIA',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 114,
                     'descripcion' => 'TOTAL SRVCIO: RESTAURANTE',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 165,
                     'descripcion' => 'TOTAL TRANSFORMACIÒN DE ORO',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 243,
                     'descripcion' => 'TOTAL COMPRA DE INVENTARIO EN CONSIGNACIÓN',
                     'cuenta' => 110505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,

                 ),
                 array(
                     'concepto_contable_id' => 140,
                     'descripcion' => 'RTE FTE CUENTA POR COBRAR: A TERCEROS',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 3,
                     'descripcion' => 'RTE FTE COMPRAS: PROPIEDAD RAIZ O EDIFICACIONES',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 8,
                     'descripcion' => 'RTE FTE COMPRAS: ACTIVOS FIJOS:CAJA FUERTE, ETC',
                     'cuenta' => 23654001,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 186,
                     'descripcion' => 'RTE FTE SERVICIO DE DIGITACION',
                     'cuenta' => 23652503,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 154,
                     'descripcion' => 'RTE FTE TRASLADO DE FONDOS SALIDA',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                array(
                    'concepto_contable_id' => 167,
                    'descripcion' => 'RTE FTE TRASLADO DE FONDOS DATAFONO SALIDA',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 332,
                    'descripcion' => 'RTE FTE OPERACIONES EFECTY',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 39,
                    'descripcion' => 'RTE FTE IMPUESTO: DE RETEICA',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 102,
                    'descripcion' => 'RTE FTE SS PF: ENTIDADES PROMOTORAS DE SALUD EPS',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 104,
                    'descripcion' => 'RTE FTE SS PF: ADMIN DE RIESGOS LABORALES, ARL',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 105,
                    'descripcion' => 'RTE FTE SS PF: CAJA DE COMPENSACION FAMILIAR',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 103,
                    'descripcion' => 'RTE FTE SS PF: FONDOS DE PENSIONES AFP',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 182,
                    'descripcion' => 'RTE FTE CXP A TERCEROS',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 141,
                    'descripcion' => 'RTE FTE CANCELACION PLAN SEPARE',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 192,
                    'descripcion' => 'RTE FTE CANC. ANTICIPO FABRICACIÓN JOYERÍA',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 172,
                    'descripcion' => 'RTE FTE REVISORIA FISCAL',
                    'cuenta' => 23651501,
                    'movimiento' => 'C',
                    'iva' => 19,
                    'total' => 119,
                ),
                array(
                    'concepto_contable_id' => 20,
                    'descripcion' => 'RTE FTE DOTACIÓN EMPLEADOS Y SUMINISTROS',
                    'cuenta' => 23654001,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 105,
                    'descripcion' => 'RTE FTE DISTRIBUCIÓN CAJA COMP. FAMILIAR',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 166,
                    'descripcion' => 'RTE FTE ASCESORIAS COMERCIALES',
                    'cuenta' => 23651501,
                    'movimiento' => 'C',
                    'iva' => 19,
                    'total' => 119,
                ),
                array(
                    'concepto_contable_id' => 5,
                    'descripcion' => 'RTE FTE ASESORIA EXTERNAS: JURIDICAS(ABOGADOS)',
                    'cuenta' => 23651501,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 5,
                    'descripcion' => 'RTE FTE ASESORIA EXTERNAS: OTROS',
                    'cuenta' => 23651501,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 40,
                    'descripcion' => 'RTE FTE IMPUESTO: INDUSTRIA Y COMERCIO',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 3,
                    'descripcion' => 'RTE FTE ARRENDMTO: PROP RAIZ(LOC) AGUIRRE E HIJO',
                    'cuenta' => 23653001,
                    'movimiento' => 'C',
                    'iva' => 19,
                    'total' => 119,
                ),
                array(
                    'concepto_contable_id' => 45,
                    'descripcion' => 'RTE FTE ARRENDMTO: EQUIPOS DE OFICINA',
                    'cuenta' => 23653002,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 5,
                    'descripcion' => 'RTE FTE ASESORIA EXTERNAS: FENACOVEN',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 115,
                    'descripcion' => 'RTE FTE SRVCIO: ASEO Y VIGILANCIA',
                    'cuenta' => 23652502,
                    'movimiento' => 'C',
                    'iva' => 1.9,
                    'total' => 101.9,
                ),
                array(
                    'concepto_contable_id' => 125,
                    'descripcion' => 'RTE FTE SRVCIOS PUBLIC: AGUA Y ALCANTARILLADO',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 121,
                    'descripcion' => 'RTE FTE SRVCIOS PUBLIC: ENERGÍA',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 122,
                    'descripcion' => 'RTE FTE SRVCIOS PUBLIC: INTERNET JEFE ZONAL',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 19,
                    'total' => 119,
                ),
                array(
                    'concepto_contable_id' => 126,
                    'descripcion' => 'RTE FTE SRVCIOS PUBLIC: AVANTEL',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 19,
                    'total' => 119,
                ),
                array(
                    'concepto_contable_id' => 123,
                    'descripcion' => 'RTE FTE SRVCIOS PUBLIC: TELÉFONO',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 19,
                    'total' => 119,
                ),
                array(
                    'concepto_contable_id' => 122,
                    'descripcion' => 'RTE FTE SRVCIOS PUBLIC: INTERNET',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 19,
                    'total' => 119,
                ),
                array(
                    'concepto_contable_id' => 97,
                    'descripcion' => 'RTE FTE PUBLICIDAD: RADIAL',
                    'cuenta' => 23652503,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 127,
                    'descripcion' => 'RTE FTE SRVCIOS PUBLIC: OTRAS ENTIDADES',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 199,
                    'descripcion' => 'RTE FTE SERVICIO LOGISTICA',
                    'cuenta' => 23652503,
                    'movimiento' => 'C',
                    'iva' => 19,
                    'total' => 119,
                ),
                array(
                    'concepto_contable_id' => 111,
                    'descripcion' => 'RTE FTE SRVCIO: GARANTÍA ART. ARREGLO JOYAS-ELEC',
                    'cuenta' => 23652503,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 45,
                    'descripcion' => 'RTE FTE MANTNMTO: EQUIPOS ELECTRÓNICOS',
                    'cuenta' => 23652503,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 15,
                    'descripcion' => 'RTE FTE COMPRAS: INSUMOS CONTRATACION Y VENTAS',
                    'cuenta' => 23654001,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 45,
                    'descripcion' => 'RTE FTE MANTNMTO: EQUIPOS DE COMPUTO',
                    'cuenta' => 23652503,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 50,
                    'descripcion' => 'RTE FTE ADEC LOCATIVAS: INSTALACIONES ELECTRICAS',
                    'cuenta' => 23652503,
                    'movimiento' => 'C',
                    'iva' => 19,
                    'total' => 119,
                ),
                array(
                    'concepto_contable_id' => 50,
                    'descripcion' => 'RTE FTE MANTNMTO: REPARA ELECTRICAS-ALARMAVISIÓN',
                    'cuenta' => 23652503,
                    'movimiento' => 'C',
                    'iva' => 19,
                    'total' => 119,
                ),
                array(
                    'concepto_contable_id' => 131,
                    'descripcion' => 'RTE FTE SOSTNMTO LOCAL: ADECUACIONES LOCATIVAS',
                    'cuenta' => 23652503,
                    'movimiento' => 'C',
                    'iva' => 19,
                    'total' => 119,
                ),
                array(
                    'concepto_contable_id' => 200,
                    'descripcion' => 'RTE FTE COMISIÓN MASRED',
                    'cuenta' => 236520,
                    'movimiento' => 'C',
                    'iva' => 19,
                    'total' => 119,
                ),
                array(
                    'concepto_contable_id' => 12,
                    'descripcion' => 'RTE FTE COMPRAS: ELEMENTOS DE ASEO',
                    'cuenta' => 23654001,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 17,
                    'descripcion' => 'RTE FTE COMPRAS: UTILES DE PAPELERÍA',
                    'cuenta' => 23654001,
                    'movimiento' => 'C',
                    'iva' => 19,
                    'total' => 119,
                ),
                array(
                    'concepto_contable_id' => 16,
                    'descripcion' => 'RTE FTE COMPRAS: LITOGRAFIA',
                    'cuenta' => 23654001,
                    'movimiento' => 'C',
                    'iva' => 19,
                    'total' => 119,
                ),
                array(
                    'concepto_contable_id' => 114,
                    'descripcion' => 'RTE FTE SRVCIO: RESTAURANTE',
                    'cuenta' => 23652505,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 165,
                    'descripcion' => 'RTE FTE TRANSFORMACIÒN DE ORO',
                    'cuenta' => 23652503,
                    'movimiento' => 'C',
                    'iva' => 19,
                    'total' => 119,
                ),
                array(
                    'concepto_contable_id' => 243,
                    'descripcion' => 'RTE FTE COMPRA DE INVENTARIO EN CONSIGNACIÓN',
                    'cuenta' => 23654004,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,

                ),
                array(
                    'concepto_contable_id' => 140,
                    'descripcion' => 'RTE ICA CUENTA POR COBRAR: A TERCEROS',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 0.0,
                    'total' => 100,
                ),
                array(
                    'concepto_contable_id' => 3,
                    'descripcion' => 'RTE ICA COMPRAS: PROPIEDAD RAIZ O EDIFICACIONES',
                    'cuenta' => 0,
                    'movimiento' => 'C',
                    'iva' => 19,
                    'total' => 119,
                ),
                array(
                    'concepto_contable_id' => 8,
                    'descripcion' => 'RTE ICA COMPRAS: ACTIVOS FIJOS:CAJA FUERTE, ETC',
                    'cuenta' => 23680510,
                    'movimiento' => 'C',
                    'iva' => 19,
                    'total' => 119,
                ),
                 array(
                     'concepto_contable_id' => 186,
                     'descripcion' => 'RTE ICA SERVICIO DE DIGITACION',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 154,
                     'descripcion' => 'RTE ICA TRASLADO DE FONDOS SALIDA',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 167,
                     'descripcion' => 'RTE ICA TRASLADO DE FONDOS DATAFONO SALIDA',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 332,
                     'descripcion' => 'RTE ICA OPERACIONES EFECTY',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 39,
                     'descripcion' => 'RTE ICA IMPUESTO: DE RETEICA',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 102,
                     'descripcion' => 'RTE ICA SS PF: ENTIDADES PROMOTORAS DE SALUD EPS',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 104,
                     'descripcion' => 'RTE ICA SS PF: ADMIN DE RIESGOS LABORALES, ARL',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 105,
                     'descripcion' => 'RTE ICA SS PF: CAJA DE COMPENSACION FAMILIAR',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 103,
                     'descripcion' => 'RTE ICA SS PF: FONDOS DE PENSIONES AFP',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 182,
                     'descripcion' => 'RTE ICA CXP A TERCEROS',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 141,
                     'descripcion' => 'RTE ICA CANCELACION PLAN SEPARE',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 192,
                     'descripcion' => 'RTE ICA CANC. ANTICIPO FABRICACIÓN JOYERÍA',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 172,
                     'descripcion' => 'RTE ICA REVISORIA FISCAL',
                     'cuenta' => 236805,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 20,
                     'descripcion' => 'RTE ICA DOTACIÓN EMPLEADOS Y SUMINISTROS',
                     'cuenta' => 23680510,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 105,
                     'descripcion' => 'RTE ICA DISTRIBUCIÓN CAJA COMP. FAMILIAR',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 166,
                     'descripcion' => 'RTE ICA ASCESORIAS COMERCIALES',
                     'cuenta' => 23680505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 5,
                     'descripcion' => 'RTE ICA ASESORIA EXTERNAS: JURIDICAS(ABOGADOS)',
                     'cuenta' => 23680505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 5,
                     'descripcion' => 'RTE ICA ASESORIA EXTERNAS: OTROS',
                     'cuenta' => 23680505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 40,
                     'descripcion' => 'RTE ICA IMPUESTO: INDUSTRIA Y COMERCIO',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 3,
                     'descripcion' => 'RTE ICA ARRENDMTO: PROP RAIZ(LOC) AGUIRRE E HIJO',
                     'cuenta' => 23680505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 45,
                     'descripcion' => 'RTE ICA ARRENDMTO: EQUIPOS DE OFICINA',
                     'cuenta' => 23680505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 5,
                     'descripcion' => 'RTE ICA ASESORIA EXTERNAS: FENACOVEN',
                     'cuenta' => 23680505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 115,
                     'descripcion' => 'RTE ICA SRVCIO: ASEO Y VIGILANCIA',
                     'cuenta' => 23680505,
                     'movimiento' => 'C',
                     'iva' => 1.9,
                     'total' => 101.9,
                 ),
                 array(
                     'concepto_contable_id' => 125,
                     'descripcion' => 'RTE ICA SRVCIOS PUBLIC: AGUA Y ALCANTARILLADO',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 121,
                     'descripcion' => 'RTE ICA SRVCIOS PUBLIC: ENERGÍA',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 122,
                     'descripcion' => 'RTE ICA SRVCIOS PUBLIC: INTERNET JEFE ZONAL',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 126,
                     'descripcion' => 'RTE ICA SRVCIOS PUBLIC: AVANTEL',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 123,
                     'descripcion' => 'RTE ICA SRVCIOS PUBLIC: TELÉFONO',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 122,
                     'descripcion' => 'RTE ICA SRVCIOS PUBLIC: INTERNET',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 97,
                     'descripcion' => 'RTE ICA PUBLICIDAD: RADIAL',
                     'cuenta' => 23680505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 127,
                     'descripcion' => 'RTE ICA SRVCIOS PUBLIC: OTRAS ENTIDADES',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 199,
                     'descripcion' => 'RTE ICA SERVICIO LOGISTICA',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 111,
                     'descripcion' => 'RTE ICA SRVCIO: GARANTÍA ART. ARREGLO JOYAS-ELEC',
                     'cuenta' => 23680505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 45,
                     'descripcion' => 'RTE ICA MANTNMTO: EQUIPOS ELECTRÓNICOS',
                     'cuenta' => 23680505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 15,
                     'descripcion' => 'RTE ICA COMPRAS: INSUMOS CONTRATACION Y VENTAS',
                     'cuenta' => 23680510,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 45,
                     'descripcion' => 'RTE ICA MANTNMTO: EQUIPOS DE COMPUTO',
                     'cuenta' => 23680505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 50,
                     'descripcion' => 'RTE ICA ADEC LOCATIVAS: INSTALACIONES ELECTRICAS',
                     'cuenta' => 23680505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 50,
                     'descripcion' => 'RTE ICA MANTNMTO: REPARA ELECTRICAS-ALARMAVISIÓN',
                     'cuenta' => 23680505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 131,
                     'descripcion' => 'RTE ICA SOSTNMTO LOCAL: ADECUACIONES LOCATIVAS',
                     'cuenta' => 23680505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 200,
                     'descripcion' => 'RTE ICA COMISIÓN MASRED',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 12,
                     'descripcion' => 'RTE ICA COMPRAS: ELEMENTOS DE ASEO',
                     'cuenta' => 23680510,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 17,
                     'descripcion' => 'RTE ICA COMPRAS: UTILES DE PAPELERÍA',
                     'cuenta' => 23680510,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 16,
                     'descripcion' => 'RTE ICA COMPRAS: LITOGRAFIA',
                     'cuenta' => 23680510,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 114,
                     'descripcion' => 'RTE ICA SRVCIO: RESTAURANTE',
                     'cuenta' => 23680505,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 165,
                     'descripcion' => 'RTE ICA TRANSFORMACIÒN DE ORO',
                     'cuenta' => 23680505,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 243,
                     'descripcion' => 'RTE ICA COMPRA DE INVENTARIO EN CONSIGNACIÓN',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,

                 ),
                 array(
                     'concepto_contable_id' => 140,
                     'descripcion' => 'RTE IVA CUENTA POR COBRAR: A TERCEROS',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 3,
                     'descripcion' => 'RTE IVA COMPRAS: PROPIEDAD RAIZ O EDIFICACIONES',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 8,
                     'descripcion' => 'RTE IVA COMPRAS: ACTIVOS FIJOS:CAJA FUERTE, ETC',
                     'cuenta' => 2367011502,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 186,
                     'descripcion' => 'RTE IVA SERVICIO DE DIGITACION',
                     'cuenta' => 2367011501,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 154,
                     'descripcion' => 'RTE IVA TRASLADO DE FONDOS SALIDA',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 167,
                     'descripcion' => 'RTE IVA TRASLADO DE FONDOS DATAFONO SALIDA',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 332,
                     'descripcion' => 'RTE IVA OPERACIONES EFECTY',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                      'iva' => 0.0,
                      'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 39,
                     'descripcion' => 'RTE IVA IMPUESTO: DE RETEICA',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 102,
                     'descripcion' => 'RTE IVA SS PF: ENTIDADES PROMOTORAS DE SALUD EPS',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 104,
                     'descripcion' => 'RTE IVA SS PF: ADMIN DE RIESGOS LABORALES, ARL',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 105,
                     'descripcion' => 'RTE IVA SS PF: CAJA DE COMPENSACION FAMILIAR',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 103,
                     'descripcion' => 'RTE IVA SS PF: FONDOS DE PENSIONES AFP',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 182,
                     'descripcion' => 'RTE IVA CXP A TERCEROS',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 141,
                     'descripcion' => 'RTE IVA CANCELACION PLAN SEPARE',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 192,
                     'descripcion' => 'RTE IVA CANC. ANTICIPO FABRICACIÓN JOYERÍA',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 172,
                     'descripcion' => 'RTE IVA REVISORIA FISCAL',
                     'cuenta' => 2367011501,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 20,
                     'descripcion' => 'RTE IVA DOTACIÓN EMPLEADOS Y SUMINISTROS',
                     'cuenta' => 2367011504,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 105,
                     'descripcion' => 'RTE IVA DISTRIBUCIÓN CAJA COMP. FAMILIAR',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 166,
                     'descripcion' => 'RTE IVA ASCESORIAS COMERCIALES',
                     'cuenta' => 2367011501,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 5,
                     'descripcion' => 'RTE IVA ASESORIA EXTERNAS: JURIDICAS(ABOGADOS)',
                     'cuenta' => 2367011503,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 5,
                     'descripcion' => 'RTE IVA ASESORIA EXTERNAS: OTROS',
                     'cuenta' => 2367011503,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 40,
                     'descripcion' => 'RTE IVA IMPUESTO: INDUSTRIA Y COMERCIO',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 3,
                     'descripcion' => 'RTE IVA ARRENDMTO: PROP RAIZ(LOC) AGUIRRE E HIJO',
                     'cuenta' => 2367011503,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 45,
                     'descripcion' => 'RTE IVA ARRENDMTO: EQUIPOS DE OFICINA',
                     'cuenta' => 2367011503,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 5,
                     'descripcion' => 'RTE IVA ASESORIA EXTERNAS: FENACOVEN',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 115,
                     'descripcion' => 'RTE IVA SRVCIO: ASEO Y VIGILANCIA',
                     'cuenta' => 2367011501,
                     'movimiento' => 'C',
                     'iva' => 1.9,
                     'total' => 101.9,
                 ),
                 array(
                     'concepto_contable_id' => 125,
                     'descripcion' => 'RTE IVA SRVCIOS PUBLIC: AGUA Y ALCANTARILLADO',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 121,
                     'descripcion' => 'RTE IVA SRVCIOS PUBLIC: ENERGÍA',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 122,
                     'descripcion' => 'RTE IVA SRVCIOS PUBLIC: INTERNET JEFE ZONAL',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 126,
                     'descripcion' => 'RTE IVA SRVCIOS PUBLIC: AVANTEL',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 123,
                     'descripcion' => 'RTE IVA SRVCIOS PUBLIC: TELÉFONO',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 122,
                     'descripcion' => 'RTE IVA SRVCIOS PUBLIC: INTERNET',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 97,
                     'descripcion' => 'RTE IVA PUBLICIDAD: RADIAL',
                     'cuenta' => 2367011503,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 127,
                     'descripcion' => 'RTE IVA SRVCIOS PUBLIC: OTRAS ENTIDADES',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 199,
                     'descripcion' => 'RTE IVA SERVICIO LOGISTICA',
                     'cuenta' => 2367011503,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 111,
                     'descripcion' => 'RTE IVA SRVCIO: GARANTÍA ART. ARREGLO JOYAS-ELEC',
                     'cuenta' => 2367011501,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 45,
                     'descripcion' => 'RTE IVA MANTNMTO: EQUIPOS ELECTRÓNICOS',
                     'cuenta' => 2367011501,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 15,
                     'descripcion' => 'RTE IVA COMPRAS: INSUMOS CONTRATACION Y VENTAS',
                     'cuenta' => 2367011502,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 45,
                     'descripcion' => 'RTE IVA MANTNMTO: EQUIPOS DE COMPUTO',
                     'cuenta' => 2367011501,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 50,
                     'descripcion' => 'RTE IVA ADEC LOCATIVAS: INSTALACIONES ELECTRICAS',
                     'cuenta' => 2367011503,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 50,
                     'descripcion' => 'RTE IVA MANTNMTO: REPARA ELECTRICAS-ALARMAVISIÓN',
                     'cuenta' => 2367011501,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 131,
                     'descripcion' => 'RTE IVA SOSTNMTO LOCAL: ADECUACIONES LOCATIVAS',
                     'cuenta' => 2367011501,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 200,
                     'descripcion' => 'RTE IVA COMISIÓN MASRED',
                     'cuenta' => 2367011503,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 12,
                     'descripcion' => 'RTE IVA COMPRAS: ELEMENTOS DE ASEO',
                     'cuenta' => 2367011502,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 17,
                     'descripcion' => 'RTE IVA COMPRAS: UTILES DE PAPELERÍA',
                     'cuenta' => 2367011502,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 16,
                     'descripcion' => 'RTE IVA COMPRAS: LITOGRAFIA',
                     'cuenta' => 2367011502,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),
                 array(
                     'concepto_contable_id' => 114,
                     'descripcion' => 'RTE IVA SRVCIO: RESTAURANTE',
                     'cuenta' => 0,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),
                 array(
                     'concepto_contable_id' => 165,
                     'descripcion' => 'RTE IVA TRANSFORMACIÒN DE ORO',
                     'cuenta' => 2367011501,
                     'movimiento' => 'C',
                     'iva' => 19,
                     'total' => 119,
                 ),

                 array(
                     'concepto_contable_id' => 243,
                     'descripcion' => 'RTE IVA COMPRA DE INVENTARIO EN CONSIGNACIÓN',
                     'cuenta' => 2367011504,
                     'movimiento' => 'C',
                     'iva' => 0.0,
                     'total' => 100,
                 ),

            )
        );
    }
}
