<table>
    <thead>
      <tr>    
        <th>CANTIDAD</th>
        <th>FECHA-VENTA</th>
        <th>jOYERIA</th>
        <th>NOMBRE-VENDEDOR</th> 
        <th>DATO_UNO</th>
        <th>DATO_DOS</th>
        <th>DATO_TRES</th>
        <th>DATO_CUATRO</th>
        <th>DATO_CINCO</th>
        <th>DATO_SEIS</th>
        <th>DATO_SIETE</th>
        <th>DATO_OCHO</th>
        <th>DATO_NUEVE</th>
        <th>DATO_DIEZ</th>
        <th>DATO_DOCE</th>
        <th>DATO_AGACHESE</th>
        <th>DATO_CATORCE</th>
        <th>DATO_QUINCE</th>
        <th>DATO_QUINCE_MAS_UNO</th>
      </tr>
    </thead>
    <tbody>
        @foreach($data as $d)
      <tr>
        <td>{{$d->cantidad}}</td>
        <td>{{$d->fecha_venta}}</td>
        <td>{{$d->nombre}}</td>
        <td>{{$d->nombre_vendedor}}</td>
        <td>{{$d->dato_uno}}</td>
        <td>{{$d->dato_dos}}</td>
        <td>{{$d->dato_tres}}</td>
        <td>{{$d->dato_cuatro}}</td>
        <td>{{$d->dato_cinco}}</td>
        <td>{{$d->dato_seis}}</td>
        <td>{{$d->dato_siete}}</td>
        <td>{{$d->dato_ocho}}</td>
        <td>{{$d->dato_nueve}}</td>
        <td>{{$d->dato_diez}}</td>
        <td>{{$d->dato_doce}}</td>
        <td>{{$d->dato_agachese}}</td>
        <td>{{$d->dato_catorce}}</td>
        <td>{{$d->dato_quince}}</td>
        <td>{{$d->dato_quince_mas_uno}}</td>
      </tr>
      @endforeach
    </tbody>
  </table>